services:
  - type: web
    name: laravel12-web
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromService:
          name: laravel12-db
          type: pserv
      - key: DB_DATABASE
        value: laravel
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: password

  - type: worker
    name: laravel12-queue
    env: docker
    dockerfilePath: ./Dockerfile
    startCommand: php artisan queue:work

  - type: worker
    name: laravel12-reverb
    env: docker
    dockerfilePath: ./Dockerfile
    startCommand: php artisan reverb:start

databases:
  - name: laravel12-db
    plan: free
